name: Go
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2.0.3
      with:
        go-version: '1.14'
      id: go
    - uses: actions/checkout@v2.1.1
    - name: Dependencies
      run: go get -t -d ./...
    - name: Build
      run: go build ./...
    - name: Test
      run: go test ./...
